### ISSUE TITLE
Feature Request: An option to hide working URLs

### ISSUE THREAD

**Issue by saneef** [bradleyburgess/eleventy-plugin-broken-links#1]
Otherwise, the build is quite verbose and the erred links are hidden deep inside the log.

**Comment by bradleyburgess** [comment]
Thanks! I agree that this would be a good option, and I will implement that
when I have a moment.

I also like the idea of being able to exclude certain pages, and being able
to `ignore` (instead of just `warn` or `error` redirects or broken links.

**Comment by bradleyburgess** [comment]
Added in `v1.3.0`.

**Comment by saneef** [comment]
This is much better! Thanks for this 🍻
