### ISSUE TITLE
Docs: Add a note to include `.cache` in `.gitignore`

### ISSUE THREAD

**Issue by saneef** [bradleyburgess/eleventy-plugin-broken-links#7]
Probably it's a good idea to include a note like ignore `.cache` like in the case of [`eleventy-fetch`](https://www.11ty.dev/docs/plugins/fetch/#installation).

**Comment by bradleyburgess** [comment]
Yes that's a good idea. My plugin isn't saving anything sensitive in there, but there is no guarantee that they (the user) aren't using other plugins / whatnot that do. So I'll definitely add that. Thanks.

**Comment by bradleyburgess** [comment]
Ok, it's live as of `v.1.3.2`.
