### ISSUE TITLE
Codepen links return 403

### ISSUE THREAD

**Issue by markdorison** [bradleyburgess/eleventy-plugin-broken-links#9]
## Description
Codepen links return 403 status code. I have verified this behavior on the command line with cURL, but the URLs work as expected in a browser.

This seems to be the case whether a URL should actually work ([200 in the browser](https://codepen.io/)) or does not exist ([404 in the browser](https://codepen.io/fhjkgfsnjkgbnxckbsjkgbnsfjkg)).

**Comment by bradleyburgess** [comment]
Fixed by [8c5d609](https://github.com/bradleyburgess/eleventy-plugin-broken-links/commit/8c5d609eae6c0ee1c3d9705b90f636e1e5fab834)
